Repository 202212-GIZ-YE-FEW/recoded_student-store_codeForce-cap, pull requests merged in 2023-05, with the labels that each got.

#96 84 favorited product component design
  src/components/FavProducts/FavProducts.jsx
  src/components/FavProducts/__test__/FavProducts.test.js
  src/components/FavProducts/__test__/__snapshots__/FavProducts.test.js.snap
  src/components/FavProducts/index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/ProductList/index.jsx
  src/layout/root/__test__/__snapshots__/RootLayout.test.js.snap
  src/pages/favorites.jsx
Labels: feature, apply-reviews, ready for review, feature (complete)

#102 update deployment domain
  src/components/FavProducts/FavProducts.jsx
  src/components/ListingItems/ListingItems.jsx
  src/components/Navbar/index.jsx
Labels: apply-reviews

#123 107 feat additional firebase authentication providers
  src/components/EditProfile/EditProfile.jsx
  src/components/FavProducts/FavProducts.jsx
  src/components/ProductList/index.jsx
  src/components/Signin/Signin.jsx
  src/components/UserListings/UserListings.jsx
  src/components/signup/index.jsx
  src/utils/firebase/auth.js
Labels: hotfix, released, apply-reviews, firebase, accessibility, ready for review, bug (complete), functionality fix

#124 103 single product
  src/components/EditProfile/EditProfile.jsx
  src/components/EditProfile/Maps.jsx
  src/components/Filter/Category/index.jsx
  src/components/ListingItems/ListingItems.jsx
  src/components/Maps.jsx
  src/components/Navbar/index.jsx
  src/components/PhotosGallery/PhotosGallery.jsx
  src/components/PhotosGallery/__test__/PhotosGallery.test.js
  src/components/PhotosGallery/__test__/__snapshots__/PhotosGallery.test.js.snap
  src/components/PhotosGallery/index.js
  src/components/ProductList/index.jsx
  src/components/UserListings/UserListings.jsx
  src/layout/root/RootLayout.jsx
  src/pages/404.jsx
  src/pages/about.jsx
  src/pages/donation.jsx
  src/pages/favorites.jsx
  src/pages/listing.jsx
  src/pages/products/[id].jsx
  src/pages/products/single-product/index.jsx
  src/pages/products/single-product/single-product.jsx
  src/pages/profile.jsx
  src/pages/signin.jsx
  src/pages/signup.jsx
  src/utils/API.js
  src/utils/store.jsx
Labels: refactor, hotfix, UX, apply-reviews, UI, complexity: 1, enhancement, feature (complete), database, functionality fix

#125 75 fix hero section
  public/images/student store.png
  src/components/hero/Hero.jsx
  src/components/hero/__test__/__snapshots__/Hero.test.js.snap
Labels: UX, UI, design, ready for review, design review, design fix

#128 Revert "121 feat add to cart"
  src/components/FavProducts/FavProducts.jsx
  src/components/Navbar/index.jsx
  src/components/ProductList/index.jsx
  src/pages/products/[id].jsx
  src/utils/store.jsx
Labels: bug 🪲, deployment

#129 fix(main): reback the reverted branch
  src/components/FavProducts/FavProducts.jsx
  src/components/ListingItems/ListingItems.jsx
  src/components/Navbar/index.jsx
  src/components/ProductList/index.jsx
  src/components/UserOrders/UserOrders.jsx
  src/pages/_app.jsx
  src/pages/products/[id].jsx
  src/utils/ErrorBundary.jsx
  src/utils/store.jsx
Labels: refactor, authentication, apply-reviews, accessibility, design, functionality fix
