Repository 202212-GIZ-YE-FEW/recoded_student-store_codeForce-cap, pull requests merged in 2023-04, with the labels that each got.

#24 15 sign up component design
  public/images/Signup_background.jpg
  public/images/hands_box.png
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/Navbar/logo.jsx
  src/components/SignUp/Signup.module.css
  src/components/SignUp/__test__/Signup.test.js
  src/components/SignUp/__test__/__snapshots__/Signup.test.js.snap
  src/components/SignUp/index.jsx
  src/pages/index.jsx
  src/styles/globals.css
Labels: feature, apply-reviews

#33 6 product filter component design
  package-lock.json
  package.json
  public/images/Book.png
  public/images/Electronic.png
  public/images/Furniture.png
  public/images/Two-wheeler.png
  src/components/Filter/Buttons/index.jsx
  src/components/Filter/Category/index.jsx
  src/components/Filter/Price/index.jsx
  src/components/Filter/index.jsx
  src/components/Navbar/Navbar.module.css
  src/components/ProductList/__test__/__snapshots__/ProductList.test.js.snap
  src/components/ProductList/index.jsx
  src/components/ProductList/products.jsx
  src/components/hero/Hero.jsx
  src/components/hero/__test__/__snapshots__/Hero.test.js.snap
  src/pages/index.jsx
  tailwind.config.js
Labels: hotfix, released, apply-reviews

#41 17 single product component design
  public/background-title.svg
  public/cat-photo.svg
  public/map.svg
  public/photo-five.svg
  public/photo-four.svg
  public/photo-one.svg
  public/photo-three.svg
  public/photo-two.svg
  src/components/SingleProduct/__test__/SingleProduct.test.js
  src/components/SingleProduct/__test__/__snapshots__/SingleProduct.test.js.snap
  src/components/SingleProduct/index.jsx
  src/pages/single-product.jsx
  tailwind.config.js
Labels: feature, UI

#45 36 create and design a dynamic button component
  .eslintrc.js
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/SignUp/__test__/__snapshots__/Signup.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SingleProduct/__test__/__snapshots__/SingleProduct.test.js.snap
  src/components/button/Button.jsx
  src/components/button/Button.stories.jsx
  src/components/button/__test__/Button.test.js
  src/components/button/__test__/__snapshots__/Button.test.js.snap
  src/components/button/index.js
  src/components/donation/Donation.stories.jsx
  src/components/donation/__test__/__snapshots__/Donation.test.js.snap
  src/components/hero/Hero.jsx
  src/components/hero/Hero.stories.jsx
  src/components/hero/__test__/__snapshots__/Hero.test.js.snap
  src/components/templates/base/BaseTemplate.stories.jsx
  src/components/templates/base/index.js
  src/layout/root/RootLayout.stories.jsx
  src/stories/Button.jsx
  src/stories/Button.stories.js
  src/stories/Button.stories.jsx
  src/stories/Header.jsx
  src/stories/Header.stories.js
  src/stories/Header.stories.jsx
  src/stories/Introduction.mdx
  src/stories/Page.stories.js
  src/stories/Page.stories.jsx
  src/stories/header.css
  src/stories/page.css
Labels: feature, 🪲bug, refactor, debug, UI

#43 37 create and design a dynamic input component
  src/components/input/Input.jsx
  src/components/input/__test__/Input.test.js
  src/components/input/__test__/__snapshots__/Input.test.js.snap
  src/components/input/index.jsx
Labels: feature

#47 42 create and design a dynamic highlighter
  src/components/Filter/Buttons/index.jsx
  src/components/Filter/Price/index.jsx
  src/components/SignUp/__test__/Signup.test.jsx
  src/components/SignUp/__test__/__snapshots__/Signup.test.jsx.snap
  src/components/highlighter/Highlighter.jsx
  src/components/highlighter/index.jsx
  tailwind.config.js
Labels: feature, apply-reviews

#54 16 sign in component design
  public/images/signin_background.jpg
  src/components/Signin/Signin.jsx
  src/components/Signin/Signin.module.css
  src/components/Signin/__test__/Signin.test.js
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/Signin/index.jsx
  src/pages/index.jsx
Labels: feature

#49 40 create and design a dynamic sidebar component
  src/components/Filter/Buttons/index.jsx
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/SideBar.stories.jsx
  src/components/SideBar/__test__/SideBar.test.jsx
  src/components/SideBar/__test__/__snapshots__/SideBar.test.jsx.snap
  src/components/SideBar/index.jsx
  src/components/highlighter/Highlighter.jsx
  src/components/highlighter/Highlighter.stories.jsx
  src/components/highlighter/__test__/Highlighter.test.jsx
  src/components/highlighter/__test__/__snapshots__/Highlighter.test.jsx.snap
Labels: refactor, hotfix, released

#53 Apply dynamic input to all inputs inside signup component
  src/components/SignUp/__test__/__snapshots__/Signup.test.jsx.snap
  src/components/SignUp/index.jsx
Labels: feature

#48 39 create and design a dynamic photo gallery component
  next.config.js
  package-lock.json
  package.json
  public/gallery.svg
  src/components/PhotosGallery/PhotosGallery.jsx
  src/components/PhotosGallery/__test__/PhotosGallery.test.js
  src/components/PhotosGallery/__test__/__snapshots__/PhotosGallery.test.js.snap
  src/components/PhotosGallery/index.js
  src/components/SignUp/__test__/Signup.test.js
  src/components/SignUp/__test__/__snapshots__/Signup.test.js.snap
  src/components/SignUp/index.jsx
  src/components/SingleProduct/__test__/__snapshots__/SingleProduct.test.js.snap
  src/pages/index.jsx
  src/pages/single-product.jsx
Labels: feature, apply-reviews, UI

#55 19 user orders component design
  src/components/ProductList/products.jsx
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/__test__/__snapshots__/SideBar.test.jsx.snap
  src/components/UserOrders/index.jsx
  src/components/UserOrders/userOrders.jsx
  src/pages/index.jsx
Labels: feature, hotfix, apply-reviews

#56 46 firebase services
  .env.enc
  .npmrc
  .nvmrc
  next.config.js
  package-lock.json
  package.json
  src/components/Filter/Category/index.jsx
  src/components/SignUp/__test__/Signup.test.js
  src/components/SignUp/__test__/__snapshots__/Signup.test.js.snap
  src/components/SignUp/index.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/SingleProduct/index.jsx
  src/components/UserOrders/userOrders.jsx
  src/components/donation/Donation.jsx
  src/components/hero/Hero.jsx
  src/components/hoc/SectionWrapper.jsx
  src/components/hoc/index.js
  src/components/input/Input.jsx
  src/components/input/__test__/__snapshots__/Input.test.js.snap
  src/pages/index.jsx
  src/pages/products/single-product/__test__/SingleProduct.test.js
  src/pages/products/single-product/__test__/__snapshots__/SingleProduct.test.js.snap
  src/pages/products/single-product/index.jsx
  src/pages/products/single-product/single-product.jsx
  src/pages/signup/Signup.module.css
  src/pages/signup/index.jsx
  src/utils/firebase/auth/signin.js
  src/utils/firebase/auth/signup.js
  src/utils/firebase/config.js
  src/utils/firebase/firestore/db.js
Labels: feature, dependencies, UX, authentication, apply-reviews, firebase

#62 test(user orders): add user orders test files
  src/components/UserOrders/__test__/UserOrders.test.js
  src/components/UserOrders/__test__/__snapshots__/UserOrders.test.js.snap
  src/components/UserOrders/index.jsx
Labels: comments

#60 52 our team component design
  package-lock.json
  package.json
  public/abdulrahman.jpg
  public/abobakr.jpg
  public/facebook-circle.svg
  public/github.svg
  public/linkedin-circle.svg
  public/marwan.jpg
  public/mohammed.jpg
  public/nabil.jpg
  public/twitter-circle.svg
  src/components/CardView/CardView.jsx
  src/components/CardView/__test__/CardView.test.js
  src/components/CardView/__test__/__snapshots__/CardView.test.js.snap
  src/components/CardView/index.js
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/OurTeam.test.js
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
  src/components/OurTeam/index.js
  src/pages/index.jsx
Labels: feature, user-story, UI

#65 21 profile edit component design
  package-lock.json
  package.json
  src/components/EditProfile/EditProfile.jsx
  src/components/EditProfile/Maps.jsx
  src/components/EditProfile/__test__/EditeProfile.test.jsx
  src/components/EditProfile/__test__/__snapshots__/EditeProfile.test.jsx.snap
  src/components/EditProfile/index.jsx
  src/components/button/Button.jsx
  src/components/input/Input.jsx
  src/pages/index.jsx
Labels: feature, dependencies, released, apply-reviews

#67 Bkr779 rename userOrders to be UserOrders
  src/components/UserOrders/UserOrders.jsx
  src/components/UserOrders/index.jsx
  src/pages/index.jsx
Labels: documentation, bug 🪲, refactor, resolve-failing-checks, comments

#68 27 story view orders listings edit
  src/components/EditProfile/EditProfile.jsx
  src/components/EditProfile/__test__/__snapshots__/EditeProfile.test.jsx.snap
  src/components/SideBar/SideBar.jsx
  src/components/SideBar/__test__/__snapshots__/SideBar.test.jsx.snap
  src/components/UserListings/UserListings.jsx
  src/components/UserOrders/UserOrders.jsx
  src/components/aboutus/__test__/__snapshots__/Aboutus.test.js.snap
  src/components/highlighter/Highlighter.jsx
  src/components/highlighter/__test__/__snapshots__/Highlighter.test.jsx.snap
  src/components/input/Input.jsx
  src/pages/index.jsx
  src/pages/user-page/index.jsx
Labels: bug 🪲, hotfix, released, user-story, apply-reviews, device: desktop, device: tablet, device: mobile, enhancement, frontend, ready for review, feature (complete)

#86 78 feat not found page
  public/empty-box.png
  src/pages/404.jsx
Labels: UI, design

#87 66 routing pages
  next.config.js
  public/abdulrahman.jpg
  public/abobakr.jpg
  public/images/Logo.png
  public/images/app-store.svg
  public/images/background-title.svg
  public/images/cat-photo.svg
  public/images/currency.svg
  public/images/empty-box.png
  public/images/facebook-circle.svg
  public/images/facebook.svg
  public/images/gallery.svg
  public/images/github.svg
  public/images/highlighter.svg
  public/images/instagram.svg
  public/images/linkedin-circle.svg
  public/images/logo-footer.svg
  public/images/map.svg
  public/images/next.svg
  public/images/photo-five.svg
  public/images/photo-four.svg
  public/images/photo-one.svg
  public/images/photo-three.svg
  public/images/photo-two.svg
  public/images/play-google.svg
  public/images/productImg.png
  public/images/thirteen.svg
  public/images/twitter-circle.svg
  public/images/twitter.svg
  public/images/up-arrow.svg
  public/marwan.jpg
  public/mohammed.jpg
  public/nabil.jpg
  src/components/CardView/CardView.jsx
  src/components/CardView/__test__/__snapshots__/CardView.test.js.snap
  src/components/EditProfile/EditProfile.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/OurTeam/OurTeam.jsx
  src/components/OurTeam/__test__/__snapshots__/OurTeam.test.js.snap
  src/components/ProductList/index.jsx
  src/components/ProductList/products.jsx
  src/components/Signin/Signin.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/aboutus/Aboutus.jsx
  src/components/aboutus/__test__/__snapshots__/Aboutus.test.js.snap
  src/components/donation/Donation.jsx
  src/components/donation/__test__/__snapshots__/Donation.test.js.snap
  src/layout/root/RootLayout.jsx
  src/layout/root/__test__/__snapshots__/RootLayout.test.js.snap
  src/pages/404.jsx
  src/pages/about-us.jsx
  src/pages/donation.jsx
  src/pages/index.jsx
  src/pages/sell-items.jsx
  src/pages/signin.jsx
  src/pages/signup/index.jsx
  src/pages/user-page.jsx
Labels: hotfix, released, apply-reviews, UI, enhancement, ready for review

#88 71 fix absolut navbar
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/layout/root/__test__/__snapshots__/RootLayout.test.js.snap
Labels: UX, UI, design review, design fix

#90 89 fix navbar search styling
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/layout/root/__test__/__snapshots__/RootLayout.test.js.snap
Labels: ready for review, design fix

#93 80 fix products animation
  src/components/Filter/Buttons/index.jsx
  src/components/ProductList/index.jsx
  src/components/UserListings/UserListings.jsx
  src/components/UserOrders/UserOrders.jsx
  src/styles/globals.css
Labels: apply-reviews, design, design fix, animation

#92 72 fix tap displayed name and logo
  public/images/tapLogo.png
  src/layout/root/RootLayout.jsx
  src/pages/user-page.jsx
Labels: hotfix, apply-reviews, enhancement, design, ready for review, feature (complete), design fix

#91 22 list product component design
  .env.enc
  .gitignore
  package-lock.json
  package.json
  public/images/emptyImage.png
  public/locales/ar/listingItems.json
  public/locales/en/listingItems.json
  src/components/Aboutus/Aboutus.jsx
  src/components/Aboutus/__test__/Aboutus.test.js
  src/components/Aboutus/__test__/__snapshots__/Aboutus.test.js.snap
  src/components/Aboutus/index.jsx
  src/components/Filter/Price/index.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Footer/index.jsx
  src/components/ListingItems/ListingItems.jsx
  src/components/ListingItems/index.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/index.jsx
  src/components/PhotosGallery/PhotosGallery.jsx
  src/components/PhotosGallery/__test__/__snapshots__/PhotosGallery.test.js.snap
  src/components/Signin/Signin.jsx
  src/components/Signin/__test__/__snapshots__/Signin.test.js.snap
  src/components/aboutus/__test__/Aboutus.test.js
  src/components/button/Button.jsx
  src/components/button/Button.stories.jsx
  src/components/input/Input.jsx
  src/layout/root/__test__/__snapshots__/RootLayout.test.js.snap
  src/pages/listing.jsx
  src/pages/products/single-product/single-product.jsx
  src/pages/profile.jsx
  src/pages/sell-items.jsx
  src/pages/signup/index.jsx
  src/utils/firebase-error-codes.js
  src/utils/firebase/add-user.js
  src/utils/firebase/auth.js
  src/utils/firebase/auth/signin.js
  src/utils/firebase/auth/signup.js
  src/utils/firebase/config.js
  src/utils/firebase/firestore/db.js
  src/utils/firebase/signin.js
  src/utils/firebase/signout.js
  src/utils/firebase/signup.js
  src/utils/firebase/waitForEmailVerification.js
  src/utils/schemaValidations/listingItems.jsx
  src/utils/schemaValidations/signin.jsx
  src/utils/schemaValidations/signup.jsx
  tailwind.config.js
Labels: feature, i18n, hotfix, apply-reviews, firebase, enhancement, frontend, ready for review, backport, feature (complete)
